# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "mysqlmaster" do |mysqlmaster|

     mysqlmaster.vm.box = "centos/7"
     mysqlmaster.vm.hostname = "mysqlmaster.dev"
  #   mysqlmaster.vm.network "forwarded_port", guest: 3306, host: 3306
     mysqlmaster.vm.network "private_network", ip: "192.168.50.1"
     mysqlmaster.vm.provision :ansible do |ansible|
        ansible.playbook = "ansible/playbooks/mysqlmaster.yml"
     end
  end

  config.vm.provider "virtualbox" do |vb|
     vb.cpus = "2"
     vb.memory = "1024"
  end

  config.vm.define "mysqlslave" do |mysqlslave|

     mysqlslave.vm.box = "centos/7"
     mysqlslave.vm.hostname = "mysqlslave.dev"
  #   mysqlslave.vm.network "forwarded_port", guest: 3306, host: 3306
     mysqlslave.vm.network "private_network", ip: "192.168.50.2"
     mysqlslave.vm.provision :ansible do |ansible|
        ansible.playbook = "ansible/playbooks/mysqlslave.yml"
     end
  end

  config.vm.provider "virtualbox" do |vb|
     vb.cpus = "2"
     vb.memory = "1024"
  end

end
