# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.vm.define "mysqlmaster" do |mysqlmaster|
     mysqlmaster.vm.box = "centos/7"
     mysqlmaster.vm.hostname = "mysqlmaster"
     mysqlmaster.vm.network "private_network", ip: "192.168.33.50", virtualbox__intnet: true
     mysqlmaster.hostmanager.aliases = %w(mysqlmaster mysqlmaster redis1)

     mysqlmaster.vm.provision "mysqlmaster", type:'ansible' do |ansible|
        ansible.playbook = "ansible/playbooks/mysqlmaster.yml"
     end
     mysqlmaster.vm.provision "redis", type:'ansible' do |ansible|
        ansible.playbook = "ansible/playbooks/redis1.yml"
     end
  end

  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.cpus = "2"
      vb.memory = "1024"
  end

  config.vm.define "mysqlslave" do |mysqlslave|
     mysqlslave.vm.box = "centos/7"
     mysqlslave.vm.hostname = "mysqlslave.local"
     mysqlslave.vm.network "private_network", ip: "192.168.33.51", virtualbox__intnet: true
     mysqlslave.hostmanager.aliases = %w(mysqlslave mysqlmaster redis2)

     mysqlslave.vm.provision "mysqlslave", type:'ansible' do |ansible|
        ansible.playbook = "ansible/playbooks/mysqlslave.yml"
     end

     mysqlslave.vm.provision "redis", type:'ansible' do |ansible|
        ansible.playbook = "ansible/playbooks/redis2.yml"
     end
  end

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.cpus = "2"
     vb.memory = "1024"
  end


  config.vm.define "node3" do |node3|
     node3.vm.box = "centos/7"
     node3.vm.hostname = "node3"
     node3.vm.network "private_network", ip: "192.168.33.52", virtualbox__intnet: true
     node3.hostmanager.aliases = %w(node3 redis3)
     
     node3.vm.provision "redis", type:'ansible' do |ansible|
        ansible.playbook = "ansible/playbooks/redis3.yml"
     end
  end

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.cpus = "1"
     vb.memory = "256"
  end

end
