# -*- mode: ruby -*-
# vi: set ft=ruby :
NODES=3
IP_PREFIX="10.10.0."
Vagrant.configure("2") do |config|
  (1..NODES).each do |i|
    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true
    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.network "private_network", ip: "#{IP_PREFIX}#{i+2}", virtualbox__intnet: true
      node.hostmanager.aliases = %w("node#{i}" "node#{i}")
      node.vm.hostname = "node#{i}"
      # map ports to host ports (for testing purposes)
      if i == NODES
        node.vm.provision "ansible" do |ansible|
          ansible.limit = "all"
          ansible.playbook = "playbooks/redis.yml"
        end
      end
    end
  end
end
